### ISSUE TITLE
Support for Tag Groups / Data Bridge API

### ISSUE THREAD

**Issue by nickbauman** [urbanairship/python-library#30]
There appears to be no way to add a device to a tag under a specific tag group even though the latest version 0.7.4 was released after the data bridge was out. Are there plans to support tag groups?

**Comment by whyqqqqq** [comment]
The next release will be out soon and will include support for tag groups.

**Comment by nickbauman** [comment]
Cool!

**Comment by pdxmele** [comment]
This should be released now. Please contact support@urbanairship.com if you run into any problems with it!
