### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by KleinCodes** [urbanairship/python-library#32]
It looks like Travis builds are failing on:

`pip install -r requirements.txt --use-mirrors`

I believe `--use-mirrors` was deprecated and removed. Any thoughts?

Build log here: https://travis-ci.org/urbanairship/python-library/jobs/158311345

**Comment by pdxmele** [comment]
Thanks for the report! We hadn't been paying attention to the Travis builds recently but we'll get this fixed up with our next release.

**Comment by madelgi** [comment]
This has been fixed. Thanks again for the report!
