### ISSUE TITLE
Update to support sending batches via `push` or `schedules`

### ISSUE THREAD

**Issue by boosh** [urbanairship/python-library#34]
The `push` and `schedules` endpoints support arrays of objects. This library should be updated to support sending batches of messages.

**Comment by pdxmele** [comment]
Hi there! Sorry, this is not yet supported. We'll try to get it into the next release, or we welcome PRs with a signed contribution agreement. Thanks!

**Comment by pdxmele** [comment]
Hi again,

Upon further review, we found that this would require major changes to the library and we have only had one request for this functionality. We’d happily review a PR but we have several higher-priority features we’d like to add first.

I'm going to close this for now, but feel free to reopen with other information about why you need this over using the library to make multiple requests.

Thanks!

**Comment by vanshsehgal2001** [comment]
Is this batching feature available now? I have an urgent requirement in my project.
