### ISSUE TITLE
ua-sphinx-docs-theme submodule is missing?

### ISSUE THREAD

**Issue by JSeligstein** [urbanairship/python-library#42]
## Expected Behavior
All referenced submodules should exist.

## Current Behavior
urbanairship/ua-sphinx-docs-theme.git as a submodule appears to be missing (or private in github)

## Possible Solution
remove submodule or make the theme available

## Steps to Reproduce
git clone project
git submodule update --init --recursive
<failure>

## Detailed Description
Here is a log:
>> git submodule update --init --recursive
source/urbanairship/docs/_themes/urbanairship'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:urbanairship/ua-sphinx-docs-theme.git' into submodule path '.../source/urbanairship/docs/_themes/urbanairship' failed
Failed to clone 'docs/_themes/urbanairship'. Retry scheduled
Cloning into '.../source/urbanairship/docs/_themes/urbanairship'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:urbanairship/ua-sphinx-docs-theme.git' into submodule path '.../source/urbanairship/docs/_themes/urbanairship' failed
Failed to clone 'docs/_themes/urbanairship' a second time, aborting
Failed to recurse into submodule path 'server/source/urbanairship'

**Comment by pdxmele** [comment]
We're going to stop using this soon and build docs another way. Sorry, and thanks for your patience!

**Comment by aschuman0** [comment]
Apologies for the very late attention to this issue. We are now using a standard sphinx theme as of 6.0.1.
