### ISSUE TITLE
openchannel sever enable faild,Do you really provide openchannel services that we can use?

### ISSUE THREAD

**Issue by jr981008** [urbanairship/python-library#46]
openchannel verification endpoint is  https://www.jrr.ink/validate
Apart from giving me an error and a hidden error page, nothing indicates that there is a problem with my endpoint. If the service is unavailable, please explain when I use it. Repeated attempts waste a lot of time.
![image](https://user-images.githubusercontent.com/20749545/72401722-c7c65d00-3787-11ea-9788-87e63c0a5860.png)
![image](https://user-images.githubusercontent.com/20749545/72401785-0eb45280-3788-11ea-98f8-52e6498f0952.png)

This is the code I provided for webhook verification, using nginx + flask
![image](https://user-images.githubusercontent.com/20749545/72401435-f1cb4f80-3786-11ea-80dd-12dfed19de5a.png)

**Comment by jr981008** [comment]
![image](https://user-images.githubusercontent.com/20749545/72401832-36a3b600-3788-11ea-9c70-800512a67789.png)
![image](https://user-images.githubusercontent.com/20749545/72401853-3f948780-3788-11ea-8031-e95d0955b65d.png)
![image](https://user-images.githubusercontent.com/20749545/72401947-7e2a4200-3788-11ea-919f-9833834bab07.png)

**Comment by aschuman0** [comment]
Hello @jr981008. This seems like an issue for our support team to handle. Please contact them at https://support.airship.com/
Thank you!
