### ISSUE TITLE
No option to create Airship object with Bearer Auth

### ISSUE THREAD

**Issue by guedes-joaofelipe** [urbanairship/python-library#51]
**All bugs, feature requests, implementation concerns or general queries should be sent to our [support team](https://support.airship.com/).**

You are welcome to submit an issue here for bugs, but please also reach out to our support team as well.

Before completing the form below, please check the following:

- [x] You are using the most recent version of the library. 
- [x] You are using a supported version of Python for that library version. 
- [x] This issue is reproducible. 

## Expected Behavior

The Airship constructor should have an option to create an object with a token instead of needing to provide an app secret and an app key. 

## Current Behavior

Developer can only create an Airship object with app key and app secret

## Possible Solution

Create an extra "token" argument in Airship to constructor and validate whether it is enough to use the class' methods

## Steps to Reproduce

1. airship = Airship(token="abcde")
2.
3.
4.

## Detailed Description

init__() got an unexpected keyword argument 'token'

**Comment by aschuman0** [comment]
Support for bearer token authentication was added in v6.0.1
