### ISSUE TITLE
API is only using global base url and giving error for EU regions. There is no place to define region so that it can take base url properly.

### ISSUE THREAD

**Issue by nitikeshd** [urbanairship/python-library#54]
**All bugs, feature requests, implementation concerns or general queries should be sent to our [support team](https://support.airship.com/).**

You are welcome to submit an issue here for bugs, but please also reach out to our support team as well.

Before completing the form below, please check the following:

- [ √] You are using the most recent version of the library. 
- [ √] You are using a supported version of Python for that library version. 
- [ √] This issue is reproducible. 

## Expected Behavior

It should take region or atleast the baseurl.

## Current Behavior

not allowing to change baseurl

## Possible Solution

we should be able to change baseurl.

## Steps to Reproduce

1. Create account in eu region
2. Install Python urbanairship library
3. Use your keys which are working fine in postman
4. you will not get authenticated

**Comment by pdxmele** [comment]
Hi, the instructions for how to switch to EU are here: https://github.com/urbanairship/python-library/blob/900569c70d46d66b7de112c8744409b1ff19f3f3/docs/index.rst#eu-base-url

Please let us know if you run into any issues with that.

**Comment by nitikeshd** [comment]
I think it was always that simple. It would be great if you can add it to the documentation as well here: https://docs.airship.com/reference/libraries/python/latest/

**Comment by pdxmele** [comment]
Yep, we've added a note to do that onto our upcoming docs refresh ticket. Thanks!

**Comment by nitikeshd** [comment]
consumer = uaconnect.Consumer(app_key, access_token, location="eu", uaconnect.FileRecorder('.offset'))

It's giving error in this case, Is there any workaround for this ?

NOTE: I am trying to get event data. Like in UI we can filter to get proper info, i am trying to do that from api.

**Comment by pdxmele** [comment]
Ok, that's a different library, can you please leave a comment there? https://github.com/urbanairship/connect-python-library/

**Comment by nitikeshd** [comment]
Sure i am adding a new issue there.

**Comment by nitikeshd** [comment]
https://github.com/urbanairship/connect-python-library/issues/6
Please use this issue id for resolute the issue.
