### ISSUE TITLE
No Global Attributes Field in the urbanairship Python Library

### ISSUE THREAD

**Issue by vanshsehgalbluecore** [urbanairship/python-library#58]
## Expected Behavior
I decided to use python library of urbanairship in my code. There is a field called global_attributes available in the push object(referring to the docs), but I am not able to find any field present in the python library.

## Current Behavior
Not able to find any global_attributes field in the push object in the python library. Its even there in the java library. Its very strange that not to have it in python library.

Please help me out if there is any way to use this field.

**Comment by pdxmele** [comment]
Hi! This is a relatively new thing, so we'll look into adding it soon. Thanks for your request!

**Comment by vanshsehgalbluecore** [comment]
Ohh. So it is not there. Thanks for confirming. Really looking forward for this to be available in urbanairship python library💯
