### ISSUE TITLE
"Europe/Kyiv" is not a valid timezone

### ISSUE THREAD

**Issue by anandtripathi5** [urbanairship/python-library#60]
## Expected Behavior
While setting the email channel we are facing an error response and the airship is not recognizing Kyiv in the timezone. I guess IANA already released the changes related to this in 2022 by renaming Kyiv from Kiev. 

It should accept timezone value "Europe/Kyiv"

```
(400, b'{"ok":false,"error":"Could not parse request body.","error_code":40000,"details":{"error":"Europe/Kyiv is not a valid timezone."}}')
```

**Comment by pdxmele** [comment]
Hi there, this is an issue with our backend API not this library, please open a support ticket for this instead at https://support.airship.com so it goes to the correct team
